@urlBase = http://localhost:3000
@user = {{urlBase}}/users


POST {{user}}/
Content-Type: application/json

{
    "dni": "2020",
    "nombre": "juan",
    "apellido": "perez",
    "email": "juan.perez@example.com",
    "contrasena": "asd123",
    "is_profe": false
}