@urlBase = http://localhost:3000
@user = {{urlBase}}/users



POST {{user}}/
Content-Type: application/json

{
    "dni": "2024",
    "nombre": "juan",
    "apellido": "perez",
    "email": "juan.pere11z@example.com",
    "contrasena": "asd123",
    "is_profe": false
}

###
GET {{user}}/login
Content-Type: application/json

{
    "mail": "juan.pere11z@example.com",
    "contrasena": "asd123"
}